---
strip_channel:
  0:
    gpionum: 21
    count: 766
    invert: 0
    brightness: 255
    strip_type: WS2811_STRIP_GRB
mapping:
  1:
  - input:
      start_address: 1
      total_rgb_channels: 168
    output:
      start_address: 0
      strip_channel: 0
  2:
  - input:
      start_address: 1
      total_rgb_channels: 168
    output:
      start_address: 168
      strip_channel: 0
  3:
  - input:
      start_address: 1
      total_rgb_channels: 168
    output:
      start_address: 336
      strip_channel: 0
  4:
  - input:
      start_address: 1
      total_rgb_channels: 168
    output:
      start_address: 504
      strip_channel: 0
